_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_victor_workspace.TrainDiffusionUnetHybridWorkspace
image_shape: &image_shape [3,300, 486]
shape_meta:
    action:
      shape:
      - 11
    obs: 
      robot_obs:
        shape:
        - 15
        type: low_dim
      image:
        shape: *image_shape
        type: rgb
      wrench_data_window:
        shape:
        - 10
        - 6
        type: time_series
      
      
      

checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-train_action_mse_error={train_action_mse_error:.3f}.ckpt
    k: 2
    mode: min
    monitor_key: val_loss # switched from mean error, train_action_mse_error

dataloader:
  batch_size: 4
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 8
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: victor_diffusion_state
  project: victor_diffusion_policy_state
  resume: true
  tags:
  - train_diffusion_unet_hybrid
  - pusht_image
  - default
multi_run:
  run_dir: victor_diffusion_state
  wandb_name_base: victor_diffusion_state
n_action_steps: 4
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  # _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_policy.DiffusionUnetHybridImagePolicy
  _target_: diffusion_policy.policy.diffusion_unet_image_policy.DiffusionUnetImagePolicy
  cond_predict_scale: true
  # crop_shape:
  # - 1
  # - 1
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  # - 128
  # - 256
  # - 512
  # eval_fixed_crop: true
  horizon: 8
  kernel_size: 5
  n_action_steps: 4
  n_groups: 8
  n_obs_steps: 2

  # noise_scheduler:
  #   _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
  #   beta_end: 0.02
  #   beta_schedule: squaredcos_cap_v2
  #   beta_start: 0.0001
  #   clip_sample: true
  #   num_train_timesteps: 100
  #   prediction_type: epsilon
  #   variance_type: fixed_small
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    # beta_schedule is important
    # this is the best we found
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: sample # or sample # or epsilon
  
  obs_encoder:
    _target_: diffusion_policy.model.vision.multi_model_obs_encoder.MultiModelObsEncoder
    shape_meta: ${shape_meta}
    rgb_model:
      _target_: diffusion_policy.model.vision.model_getter.get_resnet
      name: resnet18
      weights: IMAGENET1K_V1 # or r3m
    rgb_transform: 
      _target_: diffusion_policy.model.vision.model_getter.get_rgb_transform
      image_shape: *image_shape
      resize_shape: [256, 256]
      crop_shape: [224, 224]
      random_crop: False
      use_group_norm: False
      share_rgb_model: True
      imagenet_norm: True
    
    time_series_model:
      _target_: diffusion_policy.model.wrench.model_getter.get_wrench_encoder
      name: lstm
      input_dim: 6
      hidden_dim: 64
     


  num_inference_steps: 100
  obs_as_global_cond: true
  # obs_encoder_group_norm: true
  shape_meta: ${shape_meta}
  

task:
  dataset:
    _target_: diffusion_policy.dataset.victor_low_dim_image_dataset.VictorLowdimImageDataset
    horizon: 8
    max_train_episodes: 1
    pad_after: 0
    pad_before: 0
    seed: 42
    val_ratio: 0.05
    zarr_path: data/victor/output_data_1.zarr
    act_keys: ['robot_act']
    obs_keys: ['robot_obs','wrench_data_window']
    image_keys: ['image']


  name: victor_diff
  shape_meta: ${shape_meta}
    
task_name: victor_diff
training:
  checkpoint_every: 5
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3050
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 5
val_dataloader:
  batch_size: 4
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  shuffle: false
